# Generated by Django 4.1.4 on 2022-12-08 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nauczyciele',
            fields=[
                ('pesel', models.CharField(max_length=11, unique=True)),
                ('imie', models.CharField(max_length=45)),
                ('nazwisko', models.CharField(max_length=45)),
                ('stopienNaukowy', models.CharField(max_length=45)),
                ('tawkaGodzinowa', models.DecimalField(max_digits=5, decimal_places=2)),
            ],
            options={
                'ordering': ('pesel',),
            },
        ),
        migrations.CreateModel(
            name='Lekcje',
            fields=[
                ('id', models.IntegerField(primary_key=True)),
                ('jezyk', models.CharField(max_length=45)),
                ('data', models.DateField()),
                ('stopien', models.CharField(max_length=2)),
                ('podrecznik', models.CharField(max_length=45)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='LekcjeNauczycieli',
            fields=[
                ('pesel', models.ForeignKey('Nauczyciele', on_delete=models.CASCADE)),
                ('idLekcji', models.ForeignKey('Lekcje', on_delete=models.CASCADE)),\
            ],
            options={
                'ordering': ('pesel','idLekcji',),
            },
        ),
    ]
